### ISSUE TITLE
Save_as_webp not found

### ISSUE THREAD

**Issue by Sooxy** [dimtoneff/ComfyUI-PixelArt-Detector#1]
Hi !

Thank you for your work.
When I load the workflow.json, after having installed nodes I get this error:

_When loading the graph, the following node types were not found:
Save_as_webp
Nodes that have failed to load will show as red on the graph._

![image](https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/assets/135733534/9a2da2fb-130a-42eb-bb0f-409cf67ac7d2)

What can I do to solve the problem?

Thanks !
Sooxy

**Comment by dimtoneff** [comment]
https://github.com/dimtoneff/ComfyUI-Saveaswebp

Install my customized node and see if it works.

Here is the original Save_as_webp repo too: https://github.com/Kaharos94/ComfyUI-Saveaswebp

**Comment by dimtoneff** [comment]
Updated the repo.

- added more info about the custom webp node
- there will be two workflow versions now: default **workflow**.json and webp version **workflow_webp**.json
