### ISSUE TITLE
Ordered dithering?

### ISSUE THREAD

**Issue by tsone** [dimtoneff/ComfyUI-PixelArt-Detector#11]
Thanks for these nodes. Really useful for pixel art workflows.

Any plans for ordered dithering? With it one could get that Game Boy camera look etc. I have some Bayer dithering code I could contribute, and I'm thinking adding it  to the palette converter node. The spread for the Bayer matrix effect would be adjustable to tune the effect.

**Comment by tsone** [comment]
See https://github.com/comfyanonymous/ComfyUI/pull/1874

**Comment by dimtoneff** [comment]
I'll check it out :)

**Comment by dimtoneff** [comment]
@tsone added dithering, please check out Version 1.5 if dithering looks as expected.

**Comment by tsone** [comment]
Thanks! I also implemented dithering but in a modular way. See PR https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/pull/12
