### ISSUE TITLE
Error occured when executing PixelArtDectorSave, Module Scipy has no attribute signal

### ISSUE THREAD

**Issue by theduodecim** [dimtoneff/ComfyUI-PixelArt-Detector#15]
![fix](https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/assets/29798060/cc751a1d-0e02-4f90-bb5f-2e6af84de7e4)

Hello i'm trying for first time with ComfyUI and i get this error on Kaggle Notebook

Thanks !

**Comment by dimtoneff** [comment]
Will take care of it

**Comment by dimtoneff** [comment]
Please, try v1.5.2 and see if it fixes the error.
