### ISSUE TITLE
Error occurred when executing VAEEncode,M1

### ISSUE THREAD

**Issue by BayJ233** [dimtoneff/ComfyUI-PixelArt-Detector#17]
When I run this workflow，I met this error，my computer is M1, Macbook. Because I don’t know much about coding, I would like to ask how to solve it，thank you.
“Error occurred when executing VAEEncode:

convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function”

**Comment by dimtoneff** [comment]
Hi, not really sure how to fix this as I have no M1 and these nodes do no do VAEEncode operations. Sounds like your setup is not working properly.. does the default ComfyUI workflow work for you?

Here is a link to see how to install it on M1 Mac: https://medium.com/@ingridwickstevens/comfyui-stable-diffusion-installation-for-apple-silicon-m1-m2-m3-a7bd78e86495
