### ISSUE TITLE
[Bug] Exception while using PixelArt Palette Loader

### ISSUE THREAD

**Issue by clyce** [dimtoneff/ComfyUI-PixelArt-Detector#5]
Hello, I am currently trying out with your custom node, using ComfyUI on the current latest commit ([a57b0c7](https://github.com/comfyanonymous/ComfyUI/commit/a57b0c797b0670e6fd48ff3cf1f37dbf0d0a67b5)).
By building a simple workflow:
![image](https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/assets/1068472/56732efe-74ae-49e9-9eec-72ba0aa4dd6e)
and enqueue it, I got this error:
```
* PixelArtLoadPalettes 7:
  - Exception when validating inner node: PixelArtLoadPalettes.VALIDATE_INPUTS() got an unexpected keyword argument 'render_all_palettes_in_grid'
```

**Comment by dimtoneff** [comment]
Hi, seems that I can't reproduce your error with the ComfyUI branch you mentioned and the latest Comfy branch.
Please, try to delete the Palette Loader Node and re-add it again to the graph.

It is still working for me.
![image](https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/assets/11049957/d15c827b-f019-4634-92cd-952ab7c1b98f)
