### ISSUE TITLE
Fresh ComfyUI install, getting "(IMPORT FAILED): \custom_nodes\ComfyUI-PixelArt-Detector"

### ISSUE THREAD

**Issue by brand-brothers** [dimtoneff/ComfyUI-PixelArt-Detector#6]
Hi,
Sorry if this is a dumb question, but I followed the steps in the readme. As it didn't work, I did a fresh ComfyUI install and checked my python & dependancies were up to date. Added the pixelart Lora in the Loras folder, and the StableXL checkpoint in the checkpoints folder.
Then launched the git clone commands from the "custom_nodes" folder, they appeared to install with no errors.
But when I launch ComfyUI, I get this : 

 _File "X:\ComfyUI\custom_nodes\ComfyUI-PixelArt-Detector\pixelUtils.py", line 3, in <module>
    import cv2
**ModuleNotFoundError: No module named 'cv2'**

Cannot import X:\ComfyUI\custom_nodes\ComfyUI-PixelArt-Detector module for custom nodes: No module named 'cv2'
Loading: Save as Webp
Copying JS files for Workflow loading

Import times for custom nodes:
   0.0 seconds: X:\ComfyUI\custom_nodes\ComfyUI-Saveaswebp
   0.0 seconds (IMPORT FAILED): E:\ComfyUI\custom_nodes\ComfyUI-PixelArt-Detector_

Of course I got 4 red rectangles in Comfy, and an error popping up on:

**PixelArtLoadPalettes
PixelArtDetectorConverter
PixelArtDetectorToImage
PixelArtDetectorSave**

So I'm stuck... Anyone got the same issue ? What am I doing wrong ? Thank you.

**Comment by dimtoneff** [comment]
Weird thing is I already have had the cv2 inside my Comfy venv. Seems that another custom node might have installed it. I will add this to the requirements. Thank you for rerporting it.

**Comment by dimtoneff** [comment]
Pushed a fix.

**Comment by nour-s** [comment]
I'm still getting the same issue, I just downloaded this for the first time !

**Comment by dimtoneff** [comment]
in your venv environment:
pip install opencv-python>=4.8.0

does it work?

**Comment by DreVla** [comment]
I am getting the same error as well, just downloaded it. I solved it the same way:

> Ok nevermind, I fixed it myself by copying the cv2 folder manually in the dependancies folder created by the Comfy install.

also this: [https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/issues/7#issuecomment-1704136574](url)
