### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by GauravDe-git** [dimtoneff/ComfyUI-PixelArt-Detector#7]
Hi , firstly I'm sorry if this is not the right place to ask for help, but I didn't know how to otherwise contact the developer.

I am following all the steps in the readme:
cloning the repo in the custom nodes folder, then loading the workflow.json, but I get errors:
When loading the graph, the following node types were not found:
PixelArtLoadPalettes
PixelArtDetectorSave
PixelArtDetectorToImage
PixelArtDetectorConverter
Nodes that have failed to load will show as red on the graph.
![image](https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/assets/70570591/86bed221-6bae-496d-9487-ea088dfaca86)

**Comment by GauravDe-git** [comment]
![image](https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/assets/70570591/bbfb9cb6-a42b-44de-976d-961633a71978)
These are the import issues shown

**Comment by GauravDe-git** [comment]
Fixed it somehow..I was using the comfyUi Portable version. 
I installed the cv2 package manually and pasted the folder in ComfyUI_windows_portable\python_embeded\Lib\site-packages, now it works 🫡

**Comment by dimtoneff** [comment]
Weird thing is I already have had the cv2 inside my Comfy venv. Seems that another custom node might have installed it. I will add this to the requirements. Thank you for rerporting it.

**Comment by dimtoneff** [comment]
Pushed a fix.
