### ISSUE TITLE
cleanup_pixels_threshold

### ISSUE THREAD

**Issue by crotron** [dimtoneff/ComfyUI-PixelArt-Detector#8]
I am using the default workflow.json file in the repo and am getting an error regarding the cleanup_pixels_threshold input to PixelArt Palette Converter:

![image](https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/assets/34594223/7f2751dd-6512-493f-ae2c-677b14891e00)

It seems like this input is unconnected, making the block not run. Even stranger, when I try to resolve this by connecting a primitive to it, ComfyUI silently does nothing. Opening devtools reveals that it appears to have an infinite recursion loop when upon trying to generate. 

`Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at widgetInputs.js:22:46
    at Array.find (<anonymous>)
    at widget.serializeValue [as origSerializeValue] (widgetInputs.js:22:32)
    at widget.serializeValue [as origSerializeValue] (widgetInputs.js:27:45)
    at widget.serializeValue [as origSerializeValue] (widgetInputs.js:27:45)
    at widget.serializeValue [as origSerializeValue] (widgetInputs.js:27:45)
    at widget.serializeValue [as origSerializeValue] (widgetInputs.js:27:45)
    at widget.serializeValue [as origSerializeValue] (widgetInputs.js:27:45)
    at widget.serializeValue [as origSerializeValue] (widgetInputs.js:27:45)
    at widget.serializeValue [as origSerializeValue] (widgetInputs.js:27:45)
`

**Comment by dimtoneff** [comment]
Something has changed in Comfy. This field should of been a FLOAT input below cleanup_colors. Somehow now it ends up there... I will have to see what has changed in order to fix it

**Comment by dimtoneff** [comment]
You can see here:
https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/blob/main/img2img_webp.png?raw=true

**Comment by dimtoneff** [comment]
Here is the problematic commit:

https://github.com/comfyanonymous/ComfyUI/commit/9a7a52f8b5321e9a67fab18d4f256d2cd6bc338f

There is also a report in ComfyUI repo:
https://github.com/comfyanonymous/ComfyUI/issues/1404

Go to the place where it works:
`git checkout 0e3b64117218c50a554b492269f5f35779839695`

**Comment by dimtoneff** [comment]
Messaged the PR Author... 

https://github.com/comfyanonymous/ComfyUI/pull/1104

**Comment by M1kep** [comment]
Fix should be merged now

**Comment by dimtoneff** [comment]
Working good @M1kep! Tnx for the fast reaction!

![image](https://github.com/dimtoneff/ComfyUI-PixelArt-Detector/assets/11049957/23ee0c59-f45c-42af-b6ed-61f3e6ca340d)

**Comment by dimtoneff** [comment]
@crotron please, update your ComfyUI. Palette Converter should be fine now.

**Comment by crotron** [comment]
> @crotron please, update your ComfyUI. Palette Converter should be fine now.

Thanks, it works!
